server:
  port: 8000
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: lax
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  ssl:
    enabled: false
  forward-headers-strategy: native
spring:
  application:
    name: libertygame-achievement
  mvc:
    dispatch-options-request: true
  datasource:
    url: jdbc:oracle:thin:@achievement_high?TNS_ADMIN=${WALLET_PATH}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDR}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000
  security:
    oauth2:
      client:
        registration:
          libertygame: # 주의: scope 없어야 함 - 리버티게임 서버의 OAuth2 자동 grant 세팅을
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri : ${HOST_DOMAIN}
            client-authentication-method: client_secret_basic
            provider: libertygame
        provider:
          libertygame:
            authorization-uri: https://${HOST_OAUTH}/rest.php/oauth2/authorize
            token-uri: https://${HOST_OAUTH}/rest.php/oauth2/access_token
            user-info-uri: https://${HOST_OAUTH}/rest.php/oauth2/resource/profile
            user-name-attribute: username
jwt:
  secret: ${JWT_SECRET}
  expired: ${JWT_EXPIRED}


